import {AppRouterCacheProvider} from '@mui/material-nextjs/v15-appRouter';
import {ThemeProvider} from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import theme from '@/shared/theme';
import {Toaster} from 'react-hot-toast';
import AuthGuard from '@/shared/components/authGuard';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider options={{enableCssLayer: true}}>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <AuthGuard>{children}</AuthGuard>
            <Toaster position="top-right" reverseOrder={false} />
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
